files:
  i3_config: .config/i3/config
  launch_polybar.sh: .config/polybar/launch_polybar.sh
  polybar_config: .config/polybar/config
themes:
  boat:
    alt_bg_color: '#2b4546'
    alt_fg_color: '#86b07b'
    bg_color: '#061416'
    fg_color: '#bf9d68'
    image_name: boat.jpg
    image_path: /home/vinsho/it/arch-rice/src/ricer/wallpapers/boat.jpg
  buttons:
    alt_bg_color: '#3c2c44'
    alt_fg_color: '#89d7e7'
    bg_color: '#1c1c2c'
    fg_color: '#d8c3c9'
    image_name: buttons.png
  catpuccin:
    alt_bg_color: '#4b414b'
    alt_fg_color: '#7cc2e2'
    bg_color: '#242b3c'
    fg_color: '#daada2'
    image_name: catpuccin.png
  cottage:
    alt_bg_color: '#526f6a'
    alt_fg_color: '#82d4c6'
    bg_color: '#172a27'
    fg_color: '#e7e1bc'
    image_name: cottage.jpeg
  cthulhu:
    alt_bg_color: '#0a191f'
    alt_fg_color: '#a73b37'
    bg_color: '#202020'
    fg_color: '#459499'
    image_name: cthulhu.webp
  elephant:
    alt_bg_color: '#455957'
    alt_fg_color: '#9e9080'
    bg_color: '#31393f'
    fg_color: '#8c8284'
    image_name: wallpaper.jpg
  gruv_box_dark:
    alt_bg_color: '#32302f'
    alt_fg_color: '#6aa29d'
    bg_color: '#282828'
    fg_color: '#ebdbb2'
    image_name: cat.jpg
  pink_cloud:
    alt_bg_color: '#514150'
    alt_fg_color: '#99bcb6'
    bg_color: '#222126'
    fg_color: '#ee9d98'
    image_name: pink_cloud.jpg
  pixel_cabin:
    alt_bg_color: '#2f6252'
    alt_fg_color: '#6fbfc4'
    bg_color: '#1c3535'
    fg_color: '#c4bc77'
    image_name: pixerl_cabin.jpg
  pixel_cabin_sunset:
    alt_bg_color: '#20273d'
    alt_fg_color: '#72a5d7'
    bg_color: '#0c0c10'
    fg_color: '#f3d693'
    image_name: pixel_cabin_sunset.jpg
  pizza:
    alt_bg_color: '#6c485d'
    alt_fg_color: '#d8aeb3'
    bg_color: '#311b2b'
    fg_color: '#b5bce3'
    image_name: pizza.jpg
  samurai_bebop:
    alt_bg_color: '#32302f'
    alt_fg_color: '#f78196'
    bg_color: '#282828'
    fg_color: '#6aa29d'
    image_name: wall.png
  saturn:
    alt_bg_color: '#1b2421'
    alt_fg_color: '#788579'
    bg_color: '#050405'
    fg_color: '#ebdbb2'
    image_name: saturn.png
